version: '3.8'

services:
  # Serviço do Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: pratika_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pratika
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pratika_network

  # Serviço da API
  backend:
    build: ./backend
    container_name: pratika_api
    restart: always
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/pratika?schema=public"
      PORT: 3333
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - pratika_network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: pratika_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3333
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pratika_network

volumes:
  postgres_data:

networks:
  pratika_network:
    driver: bridge